#!/usr/bin/env python3
"""
Agent Pipeline — Business Research Report Generator
Orchestrates 4 AI agents using Claude claude-sonnet-4-6 to produce a
professional research report from a single topic string.

Usage:
    python main.py
    python main.py --topic "AI SaaS market in Dublin 2026"
"""
from __future__ import annotations

import argparse
import asyncio
import os
import re
import sys
from datetime import datetime
from pathlib import Path

import anthropic
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.rule import Rule
from rich.text import Text

from agents import AnalyzerAgent, CriticAgent, ResearcherAgent, WriterAgent
from models.schemas import DraftReport, FinalReport
from utils.logger import AgentLogger

load_dotenv()

console = Console()
pipeline_log = AgentLogger("pipeline")

OUTPUT_DIR = Path(__file__).parent / "output"
MAX_REVISION_LOOPS = 3


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------

def _draft_to_markdown(draft: DraftReport, topic: str) -> str:
    """Convert a DraftReport to full markdown content."""
    return f"""# {draft.title}

**Topic:** {topic}
**Generated:** {datetime.now().strftime("%B %d, %Y at %H:%M")}
**Report Version:** {draft.version}

---

## Executive Summary

{draft.executive_summary}

---

## Market Overview

{draft.market_overview}

---

## Key Findings

{draft.key_findings}

---

## Opportunities

{draft.opportunities}

---

## Risks & Challenges

{draft.risks}

---

## Strategic Recommendations

{draft.recommendations}

---

## Conclusion

{draft.conclusion}

---

*This report was generated by an AI agent pipeline using Claude claude-sonnet-4-6.*
"""


def _build_final_report(
    draft: DraftReport,
    topic: str,
    critic_score: int,
    iterations: int,
) -> FinalReport:
    content = _draft_to_markdown(draft, topic)
    word_count = len(content.split())
    return FinalReport(
        title=draft.title,
        topic=topic,
        content=content,
        critic_score=critic_score,
        iterations=iterations,
        generated_at=datetime.now().isoformat(),
        word_count=word_count,
    )


def _slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text[:60]


def _save_report(report: FinalReport) -> Path:
    OUTPUT_DIR.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = _slugify(report.topic)
    filename = f"{timestamp}_{slug}.md"
    path = OUTPUT_DIR / filename
    path.write_text(report.content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

async def run_pipeline(topic: str) -> FinalReport:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        console.print(
            "[bold red]Error:[/bold red] ANTHROPIC_API_KEY not set. "
            "Copy .env.example to .env and add your key."
        )
        sys.exit(1)

    client = anthropic.AsyncAnthropic(api_key=api_key)

    researcher = ResearcherAgent(client)
    analyzer = AnalyzerAgent(client)
    writer = WriterAgent(client)
    critic = CriticAgent(client)

    # ── Banner ──────────────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            Text.from_markup(
                f"[bold bright_white]Business Research Report Pipeline[/bold bright_white]\n"
                f"[dim]4 AI agents · Claude claude-sonnet-4-6 · Anthropic API[/dim]\n\n"
                f"[bold bright_cyan]Topic:[/bold bright_cyan] {topic}"
            ),
            border_style="bright_magenta",
            padding=(1, 4),
        )
    )
    console.print()

    # ── Step 1: Research ────────────────────────────────────────────────────
    with Progress(
        SpinnerColumn(spinner_name="dots", style="bright_blue"),
        TextColumn("[bright_blue]Researcher Agent working…[/bright_blue]"),
        TimeElapsedColumn(),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task("research", total=None)
        research_brief = await researcher.research(topic)

    # ── Step 2: Analysis ────────────────────────────────────────────────────
    with Progress(
        SpinnerColumn(spinner_name="dots", style="bright_green"),
        TextColumn("[bright_green]Analyzer Agent working…[/bright_green]"),
        TimeElapsedColumn(),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task("analyze", total=None)
        analysis_report = await analyzer.analyze(research_brief)

    # ── Step 3+4: Write → Critic loop ───────────────────────────────────────
    draft: DraftReport | None = None
    last_feedback = None
    approved = False
    iteration = 0

    while not approved and iteration < MAX_REVISION_LOOPS:
        iteration += 1

        # Write (or revise)
        with Progress(
            SpinnerColumn(spinner_name="dots", style="bright_yellow"),
            TextColumn(
                f"[bright_yellow]Writer Agent — draft v{iteration}…[/bright_yellow]"
            ),
            TimeElapsedColumn(),
            console=console,
            transient=True,
        ) as progress:
            progress.add_task("write", total=None)
            draft = await writer.write(
                analysis=analysis_report,
                feedback=last_feedback,
                previous_draft=draft,
                version=iteration,
            )

        # Review
        with Progress(
            SpinnerColumn(spinner_name="dots", style="bright_red"),
            TextColumn("[bright_red]Critic Agent reviewing…[/bright_red]"),
            TimeElapsedColumn(),
            console=console,
            transient=True,
        ) as progress:
            progress.add_task("review", total=None)
            last_feedback = await critic.review(draft)

        approved = last_feedback.approved

        if not approved and iteration < MAX_REVISION_LOOPS:
            pipeline_log.warning(
                f"Iteration {iteration}/{MAX_REVISION_LOOPS} — "
                f"score {last_feedback.score}/10 — requesting revision…"
            )
        elif not approved:
            pipeline_log.warning(
                f"Max iterations ({MAX_REVISION_LOOPS}) reached — "
                f"accepting best draft (score {last_feedback.score}/10)"
            )

    # ── Finalize & save ─────────────────────────────────────────────────────
    final_score = last_feedback.score if last_feedback else 0
    final_report = _build_final_report(draft, topic, final_score, iteration)
    saved_path = _save_report(final_report)

    # ── Summary ─────────────────────────────────────────────────────────────
    console.print()
    console.print(Rule(style="bright_magenta"))
    console.print(
        Panel(
            Text.from_markup(
                f"[bold bright_green]✅  Pipeline Complete![/bold bright_green]\n\n"
                f"[bold]Report:[/bold]       {final_report.title}\n"
                f"[bold]Topic:[/bold]        {topic}\n"
                f"[bold]Critic Score:[/bold] [bold {'green' if final_score >= 7 else 'yellow'}]"
                f"{final_score}/10[/bold {'green' if final_score >= 7 else 'yellow'}]\n"
                f"[bold]Iterations:[/bold]   {iteration}\n"
                f"[bold]Word Count:[/bold]   ~{final_report.word_count:,} words\n"
                f"[bold]Saved to:[/bold]     {saved_path}"
            ),
            title="[bold bright_magenta]⚡ Agent Pipeline Report[/bold bright_magenta]",
            border_style="bright_magenta",
            padding=(1, 4),
        )
    )
    console.print()

    return final_report


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Business Research Report Pipeline — 4 AI agents powered by Claude."
    )
    parser.add_argument(
        "--topic",
        type=str,
        default=None,
        help="Research topic (prompted interactively if omitted)",
    )
    args = parser.parse_args()

    topic = args.topic
    if not topic:
        console.print()
        console.print(
            "[bold bright_magenta]⚡ Business Research Report Pipeline[/bold bright_magenta]"
        )
        console.print(
            "[dim]Powered by 4 Claude claude-sonnet-4-6 agents working in sequence[/dim]"
        )
        console.print()
        topic = console.input(
            "[bold bright_cyan]Enter research topic[/bold bright_cyan] "
            "[dim](e.g. 'AI SaaS market in Dublin 2026')[/dim]: "
        ).strip()

    if not topic:
        console.print("[red]No topic provided. Exiting.[/red]")
        sys.exit(1)

    asyncio.run(run_pipeline(topic))


if __name__ == "__main__":
    main()
